name: "units-test"
on:
  pull_request:
  push:
    branches:
      - main
      - "releases/*"

jobs:
  # unit tests
  units:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Dependencies
        run: npm ci

      - name: Send Failure Notification
        if: failure()
        uses: ./
        with:
          environment: Staging
          teams-webhook-url: ${{secrets.TEAMS_WEBHOOK_URL}}
          status: "Failure"
          storybook-url: ""

      - name: Send Success Notification
        if: success()
        uses: ./
        with:
          environment: Staging
          teams-webhook-url: ${{secrets.TEAMS_WEBHOOK_URL}}
          status: "Success"
          storybook-url: ""
